### ISSUE TITLE
Fully provision drush alias file for remote use

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#58]
Fully provisioned file should look like this:
```yml
local:
  uri: machine_name.uiowa.local.site
  root: '${env.cwd}/docroot'
dev:
  uri: machine_name.dev.drupal.uiowa.edu
  host: staging-15039.prod.hosting.acquia.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
  root: /var/www/html/uiowa01.dev/docroot
  user: uiowa01.dev
prod:
  uri: machine_name.uiowa.edu
  host: web-33201.prod.hosting.acquia.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
  root: /var/www/html/uiowa01.prod/docroot
  user: uiowa01.prod
test:
  uri: machine_name.stage.drupal.uiowa.edu
  host: staging-15039.prod.hosting.acquia.com
  options: {  }
  paths:
    dump-dir: /mnt/tmp
  root: /var/www/html/uiowa01.test/docroot
  user: uiowa01.test
```
